export const RUTA_AUTH = "/auth";

export const ACCIONES_AUDITORIA = {
  REGISTRO: "REGISTRO_USUARIO",
  INICIO_SESION: "INICIO_SESION",
  CIERRE_SESION: "CIERRE_SESION",
  CIERRE_TODAS_SESIONES: "CIERRE_TODAS_SESIONES",
  TOKEN_ACTUALIZADO: "TOKEN_ACTUALIZADO",
  VERIFICACION_CORREO: "VERIFICACION_CORREO",
  SOLICITUD_RESTABLECER: "SOLICITUD_RESTABLECER_CONTRASENA",
  RESTABLECER_CONTRASENA: "RESTABLECER_CONTRASENA",
  ERROR_LOGIN: "ERROR_LOGIN",
};

export const RECURSO_AUDITORIA = {
  USUARIO: "USUARIO",
  SESION: "SESION",
  AUTH: "AUTH",
};
