import { Router } from "express";
import healthRoutes from "./health.routes";
import authRoutes from "../modules/auth/auth.routes";
import rolesRoutes from "../modules/roles/roles.routes";
import permisosRoutes from "../modules/permisos/permisos.routes";
import paisesRoutes from "../modules/paises/paises.routes";
import provinciasRoutes from "../modules/provincias/provincias.routes";
import localidadesRoutes from "../modules/localidades/localidades.routes";
import barriosRoutes from "../modules/barrios/barrios.routes";
import areasMedicasRoutes from "../modules/areas-medicas/areas-medicas.routes";
import hospitalesRoutes from "../modules/hospitales/hospitales.routes";
import sucursalesRoutes from "../modules/sucursales/sucursales.routes";
import departamentosRoutes from "../modules/departamentos/departamentos.routes";
import consultoriosRoutes from "../modules/consultorios/consultorios.routes";
import pacientesRoutes from "../modules/pacientes/pacientes.routes";
import tutoresRoutes from "../modules/tutores/tutores.routes";
import pacientesTutoresRoutes from "../modules/pacientes-tutores/pacientes-tutores.routes";
import especialidadesRoutes from "../modules/especialidades/especialidades.routes";
import medicosRoutes from "../modules/medicos/medicos.routes";
import matriculasRoutes from "../modules/matriculas/matriculas.routes";
import medicosEspecialidadesRoutes from "../modules/medicos-especialidades/medicos-especialidades.routes";
import medicosHospitalesRoutes from "../modules/medicos-hospitales/medicos-hospitales.routes";
import usersRoutes from "../modules/users/users.routes";
import availabilityRoutes from "../modules/availability/availability.routes";
import slotsRoutes from "../modules/slots/slots.routes";
import appointmentsRoutes from "../modules/appointments/appointments.routes";

const router = Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/roles", rolesRoutes);
router.use("/permisos", permisosRoutes);
router.use("/paises", paisesRoutes);
router.use("/provincias", provinciasRoutes);
router.use("/localidades", localidadesRoutes);
router.use("/barrios", barriosRoutes);
router.use("/areas-medicas", areasMedicasRoutes);
router.use("/hospitales", hospitalesRoutes);
router.use("/sucursales", sucursalesRoutes);
router.use("/departamentos", departamentosRoutes);
router.use("/consultorios", consultoriosRoutes);
router.use("/pacientes", pacientesRoutes);
router.use("/tutores", tutoresRoutes);
router.use("/pacientes-tutores", pacientesTutoresRoutes);
router.use("/especialidades", especialidadesRoutes);
router.use("/medicos", medicosRoutes);
router.use("/matriculas", matriculasRoutes);
router.use("/medicos-especialidades", medicosEspecialidadesRoutes);
router.use("/medicos-hospitales", medicosHospitalesRoutes);
router.use("/users", usersRoutes);
router.use("/availability", availabilityRoutes);
router.use("/slots", slotsRoutes);
router.use("/appointments", appointmentsRoutes);

export default router;
